# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1388779398);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 235520);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.search.order.1", "Yahoo");
user_pref("browser.search.order.2", "Ixquick");
user_pref("browser.search.order.3", "Startpage");
user_pref("browser.search.order.4", "DuckDuckGo");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131206145143");
user_pref("browser.showQuitWarning", true);
user_pref("browser.slowStartup.averageTime", 14777);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1388865678066");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1388779278065");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 24043);
user_pref("datareporting.sessions.current.main", 2);
user_pref("datareporting.sessions.current.sessionRestored", 24863);
user_pref("datareporting.sessions.current.startTime", "1388779507822");
user_pref("datareporting.sessions.current.totalTime", 68);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1388779276040,\"a\":44,\"t\":231,\"c\":true,\"m\":363,\"fp\":4574,\"sr\":5394}");
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.adblockplus.currentVersion", "2.4");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"version\":\"2.4\",\"type\":\"extension\",\"descriptor\":\"/home/micah/.mozilla/firefox/mwad0hks.default/extensions/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}.xpi\"},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"26.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"26.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.disconnect.build", 25);
user_pref("extensions.disconnect.firstBuild", 25);
user_pref("extensions.disconnect.firstUpdateThisMonthTime", "1388779525451");
user_pref("extensions.disconnect.firstUpdateThisWeekTime", "1388779525451");
user_pref("extensions.disconnect.lastUpdateTime", "1388779525451");
user_pref("extensions.disconnect.pwyw", "{\"date\":\"2014-01-03\",\"bucket\":\"viewed\"}");
user_pref("extensions.disconnect.updateCount", 1);
user_pref("extensions.disconnect.whitelist", "{\"latimes.com\":{\"Disconnect\":{\"whitelisted\":false,\"services\":{\"Google\":true}}},\"mediafire.com\":{\"Disconnect\":{\"whitelisted\":false,\"services\":{\"Facebook\":true}}},\"salon.com\":{\"Disconnect\":{\"whitelisted\":false,\"services\":{\"Google\":true}}},\"udacity.com\":{\"Disconnect\":{\"whitelisted\":false,\"services\":{\"Facebook\":true,\"Google\":true,\"Twitter\":true}}},\"freshdirect.com\":{\"Disconnect\":{\"whitelisted\":false,\"services\":{\"Google\":true}}},\"newyorker.com\":{\"Disconnect\":{\"whitelisted\":false,\"services\":{\"Google\":true}}},\"cvs.com\":{\"Advertising\":{\"whitelisted\":false,\"services\":{\"WPP\":true}}},\"deviantart.com\":{\"Disconnect\":{\"whitelisted\":false,\"services\":{\"Google\":true}}},\"hm.com\":{\"Analytics\":{\"whitelisted\":false,\"services\":{\"IBM\":true}}},\"macys.com\":{\"Analytics\":{\"whitelisted\":false,\"services\":{\"IBM\":true}}},\"nordstrom.com\":{\"Analytics\":{\"whitelisted\":false,\"services\":{\"IBM\":true}}},\"slideshare.net\":{\"Disconnect\":{\"whitelisted\":false,\"services\":{\"Facebook\":true}},\"Social\":{\"whitelisted\":false,\"services\":{\"LinkedIn\":true}}},\"target.com\":{\"Advertising\":{\"whitelisted\":false,\"services\":{\"Ensighten\":true,\"RichRelevance\":true}}},\"easyjet.com\":{\"Disconnect\":{\"whitelisted\":false,\"services\":{\"Google\":true}}},\"playtv.fr\":{\"Disconnect\":{\"whitelisted\":false,\"services\":{\"Twitter\":true}}}}");
user_pref("extensions.enabledAddons", "%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D:1.0.7,https-everywhere%40eff.org:3.4.3,2.0%40disconnect.me:3.10.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:26.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.https_everywhere._observatory.enabled", true);
user_pref("extensions.https_everywhere._observatory.popup_shown", true);
user_pref("extensions.https_everywhere.firstrun_context_menu", false);
user_pref("extensions.https_everywhere.prefs_version", 1);
user_pref("extensions.https_everywhere.toolbar_hint_shown", true);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"mint-search-enhancer@linuxmint.com\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/mint-search-enhancer@linuxmint.com\",\"mtime\":1385643431000,\"rdfTime\":1336764609000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1386344725000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1388438012000,\"rdfTime\":1386343724000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1386344725000},\"{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\",\"mtime\":1385643432000,\"rdfTime\":1336770080000}}},{\"name\":\"app-profile\",\"addons\":{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"descriptor\":\"/home/micah/.mozilla/firefox/mwad0hks.default/extensions/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}.xpi\",\"mtime\":1388779471000},\"https-everywhere@eff.org\":{\"descriptor\":\"/home/micah/.mozilla/firefox/mwad0hks.default/extensions/https-everywhere@eff.org\",\"mtime\":1388779508000,\"rdfTime\":315561600000},\"2.0@disconnect.me\":{\"descriptor\":\"/home/micah/.mozilla/firefox/mwad0hks.default/extensions/2.0@disconnect.me.xpi\",\"mtime\":1388779508000}}}]");
user_pref("extensions.lastAppVersion", "26.0");
user_pref("extensions.lastPlatformVersion", "26.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/disconnect");
user_pref("extensions.ui.locale.hidden", false);
user_pref("gecko.buildID", "20131206145143");
user_pref("gecko.mstone", "26.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("keyword.URL", "https://duckduckgo.com/?t=lm&q=");
user_pref("network.cookie.cookieBehavior", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.protocol-handler.app.apt", "/usr/bin/apturl");
user_pref("network.protocol-handler.app.apt+http", "/usr/bin/apturl");
user_pref("network.protocol-handler.warn-external.apt", true);
user_pref("network.protocol-handler.warn-external.apt+http", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 15387);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.rememberSignons", false);
user_pref("toolkit.startup.last_success", 1388779507);
user_pref("toolkit.telemetry.previousBuildID", "20131206145143");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1391371282);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
